version: '3.8'

services:
  coreai-mcu-persona:
    build:
      target: development
    image: coreai-mcu-persona-development
    container_name: coreai-mcu-persona-development
    depends_on:
      - coreai-mcu-persona-azurite
    ports:
      - "${CORE_AI_PERSONA_PORT:-3000}:3000"
      - "${CORE_AI_PERSONA_DEBUG_PORT:-9229}:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}
      INIT_STORAGE: "true"

  coreai-mcu-persona-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: coreai-mcu-persona-azurite
    ports:
      - "${CORE_AI_PERSONA_TABLE_PORT:-10002}:10002"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
