services:
  coreai-mcu-persona:
    build:
      context: .
      target: production
    image: coreai-mcu-persona
    container_name: coreai-mcu-persona
    depends_on:
      - coreai-mcu-persona-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-persona-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}

  coreai-mcu-persona-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: coreai-mcu-persona-azurite
